# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadoraFoda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalculadoraWindow(QtWidgets.QMainWindow):
    def setupUi(self, CalculadoraWindow):
        CalculadoraWindow.setObjectName("CalculadoraWindow")
        CalculadoraWindow.resize(352, 525)
        CalculadoraWindow.setStyleSheet("background-color: rgb(119, 118, 123);")
        self.centralwidget = QtWidgets.QWidget(CalculadoraWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 351, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(0, 430, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn0.setObjectName("btn0")
        self.btnComma = QtWidgets.QPushButton(self.centralwidget)
        self.btnComma.setGeometry(QtCore.QRect(90, 430, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnComma.setFont(font)
        self.btnComma.setStyleSheet("background-color: rgb(155,156,156);\n"
                                    "border-radius: 10%;\n"
                                    "color: white;")
        self.btnComma.setObjectName("btnComma")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(180, 430, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnC.setFont(font)
        self.btnC.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white;")
        self.btnC.setObjectName("btnC")
        self.btnIgual = QtWidgets.QPushButton(self.centralwidget)
        self.btnIgual.setGeometry(QtCore.QRect(270, 365, 81, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnIgual.setFont(font)
        self.btnIgual.setStyleSheet("background-color: rgb(233,116,74);\n"
                                    "border-radius: 10%;\n"
                                    "color: white")
        self.btnIgual.setObjectName("btnIgual")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(180, 365, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(90, 365, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 365, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn1.setObjectName("btn1")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(180, 300, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn6.setObjectName("btn6")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(90, 300, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn5.setObjectName("btn5")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(180, 235, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn9.setObjectName("btn9")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(90, 235, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn8.setObjectName("btn8")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 235, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn7.setObjectName("btn7")
        self.btnDivide = QtWidgets.QPushButton(self.centralwidget)
        self.btnDivide.setGeometry(QtCore.QRect(180, 170, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnDivide.setFont(font)
        self.btnDivide.setStyleSheet("background-color: rgb(59,59,59);\n"
                                     "border-radius: 10%;\n"
                                     "color: white")
        self.btnDivide.setObjectName("btnDivide")
        self.btnGpt = QtWidgets.QPushButton(self.centralwidget)
        self.btnGpt.setGeometry(QtCore.QRect(90, 170, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnGpt.setFont(font)
        self.btnGpt.setStyleSheet("background-color: rgb(59,59,59);\n"
                                  "border-radius: 10%;\n"
                                  "color: white")
        self.btnGpt.setObjectName("btnGpt")
        self.btnBlackBox = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlackBox.setGeometry(QtCore.QRect(0, 170, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBlackBox.setFont(font)
        self.btnBlackBox.setStyleSheet("background-color: rgb(59,59,59);\n"
                                       "border-radius: 10%;\n"
                                       "color: white")
        self.btnBlackBox.setObjectName("btnBlackBox")
        self.btnVezes = QtWidgets.QPushButton(self.centralwidget)
        self.btnVezes.setGeometry(QtCore.QRect(270, 170, 81, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnVezes.setFont(font)
        self.btnVezes.setStyleSheet("background-color: rgb(59,59,59);\n"
                                    "border-radius: 10%;\n"
                                    "color: white;")
        self.btnVezes.setObjectName("btnVezes")
        self.btnMenos = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenos.setGeometry(QtCore.QRect(270, 235, 81, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMenos.setFont(font)
        self.btnMenos.setStyleSheet("background-color: rgb(59,59,59);\n"
                                    "border-radius: 10%;\n"
                                    "color: white;")
        self.btnMenos.setObjectName("btnMenos")
        self.btnMais = QtWidgets.QPushButton(self.centralwidget)
        self.btnMais.setGeometry(QtCore.QRect(270, 300, 81, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnMais.setFont(font)
        self.btnMais.setStyleSheet("background-color: rgb(59,59,59);\n"
                                   "border-radius: 10%;\n"
                                   "color: white")
        self.btnMais.setObjectName("btnMais")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 300, 88, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(155,156,156);\n"
                                "border-radius: 10%;\n"
                                "color: white")
        self.btn4.setObjectName("btn4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 125, 351, 41))
        self.label.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.label.setText("")
        self.label.setObjectName("label")
        CalculadoraWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CalculadoraWindow)
        self.statusbar.setObjectName("statusbar")
        CalculadoraWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CalculadoraWindow)

        for botao in (
                self.btn0, self.btn1, self.btn2, self.btn3, self.btn4,
                self.btn5, self.btn6, self.btn7, self.btn8, self.btn9,
                self.btnMais, self.btnMenos, self.btnVezes, self.btnDivide
        ):
            botao.clicked.connect(self._adicionar_ao_visor)

            self.btnC.clicked.connect(self.limpar_tela)
            self.btnIgual.clicked.connect(self._calcular_resultado)

        QtCore.QMetaObject.connectSlotsByName(CalculadoraWindow)

    def limpar_tela(self):
        self.lcdNumber.display("0")

    def _adicionar_ao_visor(self):
        texto_botao = self.sender().text()
        self.lcdNumber.setText(self.lcdNumber.text() + texto_botao)

    def _calcular_resultado(self):
        expressao = self.lcdNumber.text()
        try:
            resultado = str(eval(expressao, {"__builtins__": None}, {}))
            self.lcdNumber.display(resultado)
        except Exception:
            self.lcdNumber.display("Erro")

    def retranslateUi(self, CalculadoraWindow):
        _translate = QtCore.QCoreApplication.translate
        CalculadoraWindow.setWindowTitle(_translate("CalculadoraWindow", "Calculadora Foda"))
        self.btn0.setText(_translate("CalculadoraWindow", "0"))
        self.btnComma.setText(_translate("CalculadoraWindow", ","))
        self.btnC.setText(_translate("CalculadoraWindow", "C"))
        self.btnIgual.setText(_translate("CalculadoraWindow", "="))
        self.btn3.setText(_translate("CalculadoraWindow", "3"))
        self.btn2.setText(_translate("CalculadoraWindow", "2"))
        self.btn1.setText(_translate("CalculadoraWindow", "1"))
        self.btn6.setText(_translate("CalculadoraWindow", "6"))
        self.btn5.setText(_translate("CalculadoraWindow", "5"))
        self.btn9.setText(_translate("CalculadoraWindow", "9"))
        self.btn8.setText(_translate("CalculadoraWindow", "8"))
        self.btn7.setText(_translate("CalculadoraWindow", "7"))
        self.btnDivide.setText(_translate("CalculadoraWindow", "÷"))
        self.btnGpt.setText(_translate("CalculadoraWindow", "GPT"))
        self.btnBlackBox.setText(_translate("CalculadoraWindow", "BlackBoxIA"))
        self.btnVezes.setText(_translate("CalculadoraWindow", "×"))
        self.btnMenos.setText(_translate("CalculadoraWindow", "-"))
        self.btnMais.setText(_translate("CalculadoraWindow", "+"))
        self.btn4.setText(_translate("CalculadoraWindow", "4"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    CalculadoraWindow = QtWidgets.QMainWindow()
    ui = Ui_CalculadoraWindow()
    ui.setupUi(CalculadoraWindow)
    CalculadoraWindow.show()
    sys.exit(app.exec_())
