# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telacalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_Display = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Display.setReadOnly(True)
        self.lineEdit_Display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Display.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Display.setFont(font)
        self.lineEdit_Display.setObjectName("lineEdit_Display")
        self.verticalLayout.addWidget(self.lineEdit_Display)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn7 = QtWidgets.QPushButton(self.widget)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 0, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.widget)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 0, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.widget)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 0, 2, 1, 1)
        self.btnDiv = QtWidgets.QPushButton(self.widget)
        self.btnDiv.setObjectName("btnDiv")
        self.gridLayout.addWidget(self.btnDiv, 0, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.widget)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 1, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.widget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 1, 1, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.widget)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 1, 2, 1, 1)
        self.btnMul = QtWidgets.QPushButton(self.widget)
        self.btnMul.setObjectName("btnMul")
        self.gridLayout.addWidget(self.btnMul, 1, 3, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.widget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 2, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.widget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 2, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.widget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 2, 2, 1, 1)
        self.btnSub = QtWidgets.QPushButton(self.widget)
        self.btnSub.setObjectName("btnSub")
        self.gridLayout.addWidget(self.btnSub, 2, 3, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.widget)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 3, 0, 1, 2)
        self.btnClear = QtWidgets.QPushButton(self.widget)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 3, 2, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.widget)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 3, 3, 1, 1)
        self.btnEqual = QtWidgets.QPushButton(self.widget)
        self.btnEqual.setObjectName("btnEqual")
        self.gridLayout.addWidget(self.btnEqual, 4, 0, 1, 4)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnMul.setText(_translate("MainWindow", "*"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btnSub.setText(_translate("MainWindow", "-"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnClear.setText(_translate("MainWindow", "C"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btnEqual.setText(_translate("MainWindow", "="))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
'''