# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputNomeFuncionario = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNomeFuncionario.setGeometry(QtCore.QRect(60, 120, 351, 27))
        self.inputNomeFuncionario.setText("")
        self.inputNomeFuncionario.setObjectName("inputNomeFuncionario")
        self.labelNomeFuncionario = QtWidgets.QLabel(self.centralwidget)
        self.labelNomeFuncionario.setGeometry(QtCore.QRect(60, 100, 131, 19))
        self.labelNomeFuncionario.setObjectName("labelNomeFuncionario")
        self.labelEndereco = QtWidgets.QLabel(self.centralwidget)
        self.labelEndereco.setGeometry(QtCore.QRect(60, 160, 131, 19))
        self.labelEndereco.setObjectName("labelEndereco")
        self.inputEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEndereco.setGeometry(QtCore.QRect(60, 180, 351, 27))
        self.inputEndereco.setText("")
        self.inputEndereco.setObjectName("inputEndereco")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 440, 161, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 440, 88, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton.clicked.connect(self.atribuir)
        self.pushButton_2.clicked.connect(MainWindow.close)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def atribuir(self):
        dados = self.inputNomeFuncionario.text()
        self.labelEndereco.setText(dados)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNomeFuncionario.setText(_translate("MainWindow", "Nome Funcionário"))
        self.labelEndereco.setText(_translate("MainWindow", "Endereço"))
        self.pushButton.setText(_translate("MainWindow", "Cadastrar Funcionário"))
        self.pushButton_2.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
